
// Returns the user based on the token sent.
GET http://localhost:3000/posts
Authorization: Bearer mytoken
###

// Deletes the refresh token.
DELETE http://localhost:3000/logout
Content-Type: application/json

{
  "token": "mytoken"
}

###

// Generates a new token based on the refresh token.
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "mytoken"
}

###

// Generates the login token and the refresh token.
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Henrique"
}